### ISSUE TITLE
Déploiement continu du site sur gh-pages

### ISSUE THREAD

**Issue by adriens** [meilie389/homepage#2]
1. Quand un commit est poussé sur `master` : builder le site avec la Github action Action Hugo et pousser le code généré sur `gh-pages`
2. Sur `README`, mettre l'url du site

Prendre exemple sur https://github.com/adriens/emploi-nc-website et surtout gérer le secret ;-p

**Comment by meilie389** [comment]
Mauvaise repo mais c'est fait sur https://github.com/meilie389/cv-online

**Comment by adriens** [comment]
la classe 😎
